switch argument0 {
    case 0:
        return 324;
    case 1:
        return 325;
    case 2:
        return 326;
    case 3:
        return 327;
    case 4:
        return 328;
    case 5:
        return 329;
    case 6:
        return 330;
    case 7:
        return 331;
    case 8:
        return 332;
    case 9:
        return 333;
    case 10:
        return 334;
    case 11:
        return 335;
    case 12:
        return 336;
    case 13:
        return 337;
    case 14:
        return 338;
    case 15:
        return 339;
    case 16:
        return 340;
    case 17:
        return 341;
    case 18:
        return 342;
    case 19:
        return 343;
    case 21:
        return asset_get_index("sprH_HeadbandBlack");
    case 22:
        return asset_get_index("sprH_HeadbandWhite");
    case 23:
        return asset_get_index("sprH_HeadbandBlue");
    case 24:
        return asset_get_index("sprH_HeadbandRed");
    case 25:
        return asset_get_index("sprH_HeadbandYellow");
    case 26:
        return asset_get_index("sprH_HeadbandPurple");
    case 501:
        return 323;
    default:
        return -1;
}
