food_lst = ds_grid_create(14, 6)
egg_lst = ds_grid_create(15, 6)
toy_lst = ds_grid_create(13, 6)
hat_lst = ds_grid_create(27, 6)
acc_lst = ds_grid_create(15, 6)
lvl1 = global._un_hatch
lvl2 = global._un_win
lvl3 = global._un_evolve
lvl4 = global._un_win2
lvl5 = global._un_winall
lvls = global._un_swim
lvlf = global._un_fly
lvlr = global._un_run
lvlp = global._un_power
lvls2 = global._un_swim_2
lvlf2 = global._un_fly_2
lvlr2 = global._un_run_2
lvlp2 = global._un_power_2
if (global.evt_holiday == 1)
    h_halloween = 0
else
    h_halloween = 2
if (global.evt_holiday == 2)
    h_thanks = 0
else
    h_thanks = 2
if (global.evt_holiday == 3)
    h_xmas = 0
else
    h_xmas = 2
page_un[0] = 0
page_un[1] = 0
page_un[2] = 0
page_un[3] = 0
page_un[4] = 0
if (global._un_hatch < 2)
    mini_p = 0
else
    mini_p = 1
page = 0
selection = 0
hold = 0
fade = 0
shift = 0
p_am = 1
c_alpha = 0
no_input = 0
prompt = -1
purchase = 0
rotate = 2
arr = 0
new = 1
alarm[2] = 30
spi_i = 0
jewel_feature = 0
spi_name[0] = "Garnet"
spi_name[1] = "Topaz"
spi_name[2] = "Emerald"
spi_name[3] = "Aquamarine"
spi_name[4] = "Sapphire"
spi_name[5] = "Amethyst"
spi_name[6] = "Ruby"
spi_name[7] = "Onyx"
spi_name[8] = "Gold"
spi_name[9] = "Silver"
spi_name[10] = "Peridot"
spi_price[0] = 3000
spi_price[1] = 3000
spi_price[2] = 4000
spi_price[3] = 4000
spi_price[4] = 3000
spi_price[5] = 4000
spi_price[6] = 5000
spi_price[7] = 10000
spi_price[8] = 8000
spi_price[9] = 2000
spi_price[10] = 15000
spi_unlock[0] = 2
spi_unlock[1] = 2
spi_unlock[2] = 2
spi_unlock[3] = 2
spi_unlock[4] = 2
spi_unlock[5] = 2
spi_unlock[6] = 2
spi_unlock[7] = 2
spi_unlock[8] = 2
spi_unlock[9] = 2
spi_unlock[10] = 2
if (lvl4 <= 1 && global.spi_egg_t <= 0) {
    spi_i = global.spi_egg
    spi_unlock[spi_i] = 0
    jewel_feature = 1
}
list = food_lst
ds_grid_add(list, 0, 0, "Orange Fruit")
ds_grid_add(list, 0, 1, 0)
ds_grid_add(list, 0, 2, 30)
ds_grid_add(list, 0, 3, "Delicious fruit!#S/P stat-based.")
ds_grid_add(list, 0, 4, 571)
ds_grid_add(list, 0, 5, 0)
ds_grid_add(list, 1, 0, "Blue Fruit")
ds_grid_add(list, 1, 1, 0)
ds_grid_add(list, 1, 2, 60)
ds_grid_add(list, 1, 3, "Delicious fruit!#F stat-based.")
ds_grid_add(list, 1, 4, 571)
ds_grid_add(list, 1, 5, 1)
ds_grid_add(list, 2, 0, "Pink Fruit")
ds_grid_add(list, 2, 1, 0)
ds_grid_add(list, 2, 2, 55)
ds_grid_add(list, 2, 3, "Delicious fruit!#S/R stat-based.")
ds_grid_add(list, 2, 4, 571)
ds_grid_add(list, 2, 5, 2)
ds_grid_add(list, 3, 0, "Green Fruit")
ds_grid_add(list, 3, 1, 0)
ds_grid_add(list, 3, 2, 50)
ds_grid_add(list, 3, 3, "Delicious fruit!#P stat-based.")
ds_grid_add(list, 3, 4, 571)
ds_grid_add(list, 3, 5, 3)
ds_grid_add(list, 4, 0, "Purple Fruit")
ds_grid_add(list, 4, 1, 0)
ds_grid_add(list, 4, 2, 30)
ds_grid_add(list, 4, 3, "Delicious fruit!#F/R stat-based.")
ds_grid_add(list, 4, 4, 571)
ds_grid_add(list, 4, 5, 4)
ds_grid_add(list, 5, 0, "Yellow Fruit")
ds_grid_add(list, 5, 1, 0)
ds_grid_add(list, 5, 2, 55)
ds_grid_add(list, 5, 3, "Delicious fruit!#F/P stat-based.")
ds_grid_add(list, 5, 4, 571)
ds_grid_add(list, 5, 5, 5)
ds_grid_add(list, 6, 0, "Red Fruit")
ds_grid_add(list, 6, 1, 0)
ds_grid_add(list, 6, 2, 70)
ds_grid_add(list, 6, 3, "Delicious fruit!#Average stat-based.")
ds_grid_add(list, 6, 4, 571)
ds_grid_add(list, 6, 5, 6)
ds_grid_add(list, 7, 0, "Star Fruit")
ds_grid_add(list, 7, 1, lvl2)
ds_grid_add(list, 7, 2, 200)
ds_grid_add(list, 7, 3, "Delicious fruit!#Max stat-based.")
ds_grid_add(list, 7, 4, 571)
ds_grid_add(list, 7, 5, 7)
ds_grid_add(list, 8, 0, "Hero Fruit")
ds_grid_add(list, 8, 1, lvl3)
ds_grid_add(list, 8, 2, 120)
ds_grid_add(list, 8, 3, "Hero trait fruit!")
ds_grid_add(list, 8, 4, 571)
ds_grid_add(list, 8, 5, 9)
ds_grid_add(list, 9, 0, "Dark Fruit")
ds_grid_add(list, 9, 1, lvl3)
ds_grid_add(list, 9, 2, 120)
ds_grid_add(list, 9, 3, "Dark trait fruit!")
ds_grid_add(list, 9, 4, 571)
ds_grid_add(list, 9, 5, 10)
ds_grid_add(list, 10, 0, "Lollipop")
ds_grid_add(list, 10, 1, lvl4)
ds_grid_add(list, 10, 2, 200)
ds_grid_add(list, 10, 3, "Delicious snack!#Increases happiness.")
ds_grid_add(list, 10, 4, 571)
ds_grid_add(list, 10, 5, 11)
ds_grid_add(list, 11, 0, "Pumpkin Bread")
ds_grid_add(list, 11, 1, h_halloween)
ds_grid_add(list, 11, 2, 80)
ds_grid_add(list, 11, 3, "Holiday snack!#P stat-based.")
ds_grid_add(list, 11, 4, 571)
ds_grid_add(list, 11, 5, 12)
ds_grid_add(list, 12, 0, "Fruit Cake")
ds_grid_add(list, 12, 1, h_xmas)
ds_grid_add(list, 12, 2, 80)
ds_grid_add(list, 12, 3, "Holiday snack!#P stat-based.")
ds_grid_add(list, 12, 4, 571)
ds_grid_add(list, 12, 5, 13)
ds_grid_add(list, 13, 0, "Heart Fruit")
ds_grid_add(list, 13, 1, lvl3)
ds_grid_add(list, 13, 2, 120)
ds_grid_add(list, 13, 3, "Egg-fertility fruit!")
ds_grid_add(list, 13, 4, 571)
ds_grid_add(list, 13, 5, 14)
list = egg_lst
ds_grid_add(list, 0, 0, (spi_name[spi_i] + " Egg"))
ds_grid_add(list, 0, 1, spi_unlock[spi_i])
ds_grid_add(list, 0, 2, spi_price[spi_i])
ds_grid_add(list, 0, 3, "Special: Extremely rare chao egg!")
ds_grid_add(list, 0, 4, 317)
ds_grid_add(list, 0, 5, spi_i)
ds_grid_add(list, 1, 0, "Normal Egg")
ds_grid_add(list, 1, 1, 0)
ds_grid_add(list, 1, 2, 200)
ds_grid_add(list, 1, 3, "Common chao egg.")
ds_grid_add(list, 1, 4, 316)
ds_grid_add(list, 1, 5, 0)
ds_grid_add(list, 2, 0, "Red Egg")
ds_grid_add(list, 2, 1, lvl1)
ds_grid_add(list, 2, 2, 500)
ds_grid_add(list, 2, 3, "Common chao egg.")
ds_grid_add(list, 2, 4, 316)
ds_grid_add(list, 2, 5, 1)
ds_grid_add(list, 3, 0, "Orange Egg")
ds_grid_add(list, 3, 1, lvl2)
ds_grid_add(list, 3, 2, 600)
ds_grid_add(list, 3, 3, "Uncommon chao egg.")
ds_grid_add(list, 3, 4, 316)
ds_grid_add(list, 3, 5, 2)
ds_grid_add(list, 4, 0, "Yellow Egg")
ds_grid_add(list, 4, 1, lvl1)
ds_grid_add(list, 4, 2, 500)
ds_grid_add(list, 4, 3, "Common chao egg.")
ds_grid_add(list, 4, 4, 316)
ds_grid_add(list, 4, 5, 3)
ds_grid_add(list, 5, 0, "Green Egg")
ds_grid_add(list, 5, 1, lvl2)
ds_grid_add(list, 5, 2, 600)
ds_grid_add(list, 5, 3, "Uncommon chao egg.")
ds_grid_add(list, 5, 4, 316)
ds_grid_add(list, 5, 5, 4)
ds_grid_add(list, 6, 0, "Sky Blue Egg")
ds_grid_add(list, 6, 1, lvl2)
ds_grid_add(list, 6, 2, 600)
ds_grid_add(list, 6, 3, "Uncommon chao egg.")
ds_grid_add(list, 6, 4, 316)
ds_grid_add(list, 6, 5, 5)
ds_grid_add(list, 7, 0, "Blue Egg")
ds_grid_add(list, 7, 1, lvl1)
ds_grid_add(list, 7, 2, 500)
ds_grid_add(list, 7, 3, "Common chao egg.")
ds_grid_add(list, 7, 4, 316)
ds_grid_add(list, 7, 5, 6)
ds_grid_add(list, 8, 0, "Purple Egg")
ds_grid_add(list, 8, 1, lvl2)
ds_grid_add(list, 8, 2, 600)
ds_grid_add(list, 8, 3, "Uncommon chao egg.")
ds_grid_add(list, 8, 4, 316)
ds_grid_add(list, 8, 5, 7)
ds_grid_add(list, 9, 0, "Pink Egg")
ds_grid_add(list, 9, 1, lvl4)
ds_grid_add(list, 9, 2, 600)
ds_grid_add(list, 9, 3, "Rare chao egg!")
ds_grid_add(list, 9, 4, 316)
ds_grid_add(list, 9, 5, 8)
ds_grid_add(list, 10, 0, "White Egg")
ds_grid_add(list, 10, 1, lvl4)
ds_grid_add(list, 10, 2, 400)
ds_grid_add(list, 10, 3, "Rare chao egg!")
ds_grid_add(list, 10, 4, 316)
ds_grid_add(list, 10, 5, 9)
ds_grid_add(list, 11, 0, "Black Egg")
ds_grid_add(list, 11, 1, lvl4)
ds_grid_add(list, 11, 2, 2000)
ds_grid_add(list, 11, 3, "Very rare chao egg!")
ds_grid_add(list, 11, 4, 316)
ds_grid_add(list, 11, 5, 10)
ds_grid_add(list, 12, 0, "Brown Egg")
ds_grid_add(list, 12, 1, lvl4)
ds_grid_add(list, 12, 2, 800)
ds_grid_add(list, 12, 3, "Rare chao egg!")
ds_grid_add(list, 12, 4, 316)
ds_grid_add(list, 12, 5, 11)
ds_grid_add(list, 13, 0, "Gray Egg")
ds_grid_add(list, 13, 1, lvl4)
ds_grid_add(list, 13, 2, 1000)
ds_grid_add(list, 13, 3, "Very rare chao egg!")
ds_grid_add(list, 13, 4, 316)
ds_grid_add(list, 13, 5, 12)
ds_grid_add(list, 14, 0, "Lime Egg")
ds_grid_add(list, 14, 1, lvl4)
ds_grid_add(list, 14, 2, 1500)
ds_grid_add(list, 14, 3, "Very rare chao egg!")
ds_grid_add(list, 14, 4, 316)
ds_grid_add(list, 14, 5, 13)
list = toy_lst
ds_grid_add(list, 0, 0, "Toy Trumpet")
ds_grid_add(list, 0, 1, lvl1)
ds_grid_add(list, 0, 2, 200)
ds_grid_add(list, 0, 3, "Instrument that makes a sound!")
ds_grid_add(list, 0, 4, 13)
ds_grid_add(list, 0, 5, 0)
ds_grid_add(list, 1, 0, "Rubber Duck")
ds_grid_add(list, 1, 1, lvl1)
ds_grid_add(list, 1, 2, 200)
ds_grid_add(list, 1, 3, "Toy for beginning swimmers!")
ds_grid_add(list, 1, 4, 11)
ds_grid_add(list, 1, 5, 0)
ds_grid_add(list, 2, 0, "Mini TV")
ds_grid_add(list, 2, 1, lvlp)
ds_grid_add(list, 2, 2, 2000)
ds_grid_add(list, 2, 3, "Small TV with free cable!")
ds_grid_add(list, 2, 4, 12)
ds_grid_add(list, 2, 5, 0)
ds_grid_add(list, 3, 0, "Sonic Doll")
ds_grid_add(list, 3, 1, lvlr)
ds_grid_add(list, 3, 2, 1500)
ds_grid_add(list, 3, 3, "Doll that resembles Sonic!")
ds_grid_add(list, 3, 4, 9)
ds_grid_add(list, 3, 5, 0)
ds_grid_add(list, 4, 0, "Shadow Doll")
ds_grid_add(list, 4, 1, lvlr)
ds_grid_add(list, 4, 2, 1500)
ds_grid_add(list, 4, 3, "Doll that resembles Shadow!")
ds_grid_add(list, 4, 4, 15)
ds_grid_add(list, 4, 5, 0)
ds_grid_add(list, 5, 0, "Rubber Ball")
ds_grid_add(list, 5, 1, lvl1)
ds_grid_add(list, 5, 2, 400)
ds_grid_add(list, 5, 3, "Bouncy ball to play with!")
ds_grid_add(list, 5, 4, 4)
ds_grid_add(list, 5, 5, 0)
ds_grid_add(list, 6, 0, "Soccer Ball")
ds_grid_add(list, 6, 1, lvl5)
ds_grid_add(list, 6, 2, 500)
ds_grid_add(list, 6, 3, "")
ds_grid_add(list, 6, 4, 6)
ds_grid_add(list, 6, 5, 0)
ds_grid_add(list, 7, 0, "Beach Ball")
ds_grid_add(list, 7, 1, lvls)
ds_grid_add(list, 7, 2, 1000)
ds_grid_add(list, 7, 3, "Inflated ball for a pool party!")
ds_grid_add(list, 7, 4, 5)
ds_grid_add(list, 7, 5, 0)
ds_grid_add(list, 8, 0, "Mini Car")
ds_grid_add(list, 8, 1, lvlr2)
ds_grid_add(list, 8, 2, 2500)
ds_grid_add(list, 8, 3, "Be sure to buckle up!")
ds_grid_add(list, 8, 4, 10)
ds_grid_add(list, 8, 5, 0)
ds_grid_add(list, 9, 0, "Toy Radio")
ds_grid_add(list, 9, 1, lvlf)
ds_grid_add(list, 9, 2, 2000)
ds_grid_add(list, 9, 3, "Listen to music and sing along!")
ds_grid_add(list, 9, 4, 14)
ds_grid_add(list, 9, 5, 0)
ds_grid_add(list, 10, 0, "Toy Boat")
ds_grid_add(list, 10, 1, lvls2)
ds_grid_add(list, 10, 2, 2000)
ds_grid_add(list, 10, 3, "All aboard the S.S. CRI!")
ds_grid_add(list, 10, 4, 18)
ds_grid_add(list, 10, 5, 0)
ds_grid_add(list, 11, 0, "Hot Air Balloon")
ds_grid_add(list, 11, 1, lvlf2)
ds_grid_add(list, 11, 2, 2500)
ds_grid_add(list, 11, 3, "The sky's the limit!")
ds_grid_add(list, 11, 4, 19)
ds_grid_add(list, 11, 5, 0)
ds_grid_add(list, 12, 0, "Rocking Horse")
ds_grid_add(list, 12, 1, lvlp2)
ds_grid_add(list, 12, 2, 1800)
ds_grid_add(list, 12, 3, "Giddy up cowboy!")
ds_grid_add(list, 12, 4, 16)
ds_grid_add(list, 12, 5, 0)
list = hat_lst
ds_grid_add(list, 0, 0, "Baseball Cap")
ds_grid_add(list, 0, 1, lvl1)
ds_grid_add(list, 0, 2, 200)
ds_grid_add(list, 0, 3, "Great game out there!")
ds_grid_add(list, 0, 4, 324)
ds_grid_add(list, 0, 5, 0)
ds_grid_add(list, 1, 0, "Headphones")
ds_grid_add(list, 1, 1, lvl2)
ds_grid_add(list, 1, 2, 200)
ds_grid_add(list, 1, 3, "Sick pair for music lovers.")
ds_grid_add(list, 1, 4, 325)
ds_grid_add(list, 1, 5, 1)
ds_grid_add(list, 2, 0, "Top Hat")
ds_grid_add(list, 2, 1, lvl2)
ds_grid_add(list, 2, 2, 200)
ds_grid_add(list, 2, 3, "Tall topper for the sophisticated.")
ds_grid_add(list, 2, 4, 326)
ds_grid_add(list, 2, 5, 2)
ds_grid_add(list, 3, 0, "Beanie")
ds_grid_add(list, 3, 1, lvl1)
ds_grid_add(list, 3, 2, 200)
ds_grid_add(list, 3, 3, "Warm beanie for the cold weather.")
ds_grid_add(list, 3, 4, 327)
ds_grid_add(list, 3, 5, 3)
ds_grid_add(list, 4, 0, "Press Hat")
ds_grid_add(list, 4, 1, lvl2)
ds_grid_add(list, 4, 2, 200)
ds_grid_add(list, 4, 3, "'Extra! Extra!'")
ds_grid_add(list, 4, 4, 328)
ds_grid_add(list, 4, 5, 4)
ds_grid_add(list, 5, 0, "Feline Ears")
ds_grid_add(list, 5, 1, lvl2)
ds_grid_add(list, 5, 2, 200)
ds_grid_add(list, 5, 3, "Furry ears for cat lovers!")
ds_grid_add(list, 5, 4, 329)
ds_grid_add(list, 5, 5, 5)
ds_grid_add(list, 6, 0, "Pumpkin Head")
ds_grid_add(list, 6, 1, h_halloween)
ds_grid_add(list, 6, 2, 200)
ds_grid_add(list, 6, 3, "Holiday topper.#S P O O K Y")
ds_grid_add(list, 6, 4, 330)
ds_grid_add(list, 6, 5, 6)
ds_grid_add(list, 7, 0, "Skeleton Head")
ds_grid_add(list, 7, 1, h_halloween)
ds_grid_add(list, 7, 2, 200)
ds_grid_add(list, 7, 3, "Holiday topper.#S P O O K Y")
ds_grid_add(list, 7, 4, 331)
ds_grid_add(list, 7, 5, 7)
ds_grid_add(list, 8, 0, "C.S. Hat")
ds_grid_add(list, 8, 1, lvl2)
ds_grid_add(list, 8, 2, 200)
ds_grid_add(list, 8, 3, "Large fedora for the mystery-solver.")
ds_grid_add(list, 8, 4, 332)
ds_grid_add(list, 8, 5, 8)
ds_grid_add(list, 9, 0, "Ninja Headband")
ds_grid_add(list, 9, 1, lvl2)
ds_grid_add(list, 9, 2, 200)
ds_grid_add(list, 9, 3, "Be stealthy like a ninja.")
ds_grid_add(list, 9, 4, 333)
ds_grid_add(list, 9, 5, 9)
ds_grid_add(list, 10, 0, "Cowboy Hat")
ds_grid_add(list, 10, 1, lvl4)
ds_grid_add(list, 10, 2, 200)
ds_grid_add(list, 10, 3, "Round 'em up, partner.")
ds_grid_add(list, 10, 4, 334)
ds_grid_add(list, 10, 5, 10)
ds_grid_add(list, 11, 0, "Red Cap")
ds_grid_add(list, 11, 1, lvl2)
ds_grid_add(list, 11, 2, 200)
ds_grid_add(list, 11, 3, "The '90s were the best.")
ds_grid_add(list, 11, 4, 335)
ds_grid_add(list, 11, 5, 11)
ds_grid_add(list, 12, 0, "Rice Hat")
ds_grid_add(list, 12, 1, lvl2)
ds_grid_add(list, 12, 2, 200)
ds_grid_add(list, 12, 3, "...")
ds_grid_add(list, 12, 4, 336)
ds_grid_add(list, 12, 5, 12)
ds_grid_add(list, 13, 0, "Snow Cap")
ds_grid_add(list, 13, 1, lvl2)
ds_grid_add(list, 13, 2, 200)
ds_grid_add(list, 13, 3, "Bundle up for a cold winter.")
ds_grid_add(list, 13, 4, 337)
ds_grid_add(list, 13, 5, 13)
ds_grid_add(list, 14, 0, "Santa Hat")
ds_grid_add(list, 14, 1, h_xmas)
ds_grid_add(list, 14, 2, 200)
ds_grid_add(list, 14, 3, "Holiday topper.")
ds_grid_add(list, 14, 4, 338)
ds_grid_add(list, 14, 5, 14)
ds_grid_add(list, 15, 0, "Party Hat")
ds_grid_add(list, 15, 1, h_xmas)
ds_grid_add(list, 15, 2, 200)
ds_grid_add(list, 15, 3, "Holiday topper.")
ds_grid_add(list, 15, 4, 339)
ds_grid_add(list, 15, 5, 15)
ds_grid_add(list, 16, 0, "Beret")
ds_grid_add(list, 16, 1, lvl2)
ds_grid_add(list, 16, 2, 200)
ds_grid_add(list, 16, 3, "")
ds_grid_add(list, 16, 4, 340)
ds_grid_add(list, 16, 5, 16)
ds_grid_add(list, 17, 0, "Floppy Hat")
ds_grid_add(list, 17, 1, lvl2)
ds_grid_add(list, 17, 2, 200)
ds_grid_add(list, 17, 3, "Life's a beach.")
ds_grid_add(list, 17, 4, 341)
ds_grid_add(list, 17, 5, 17)
ds_grid_add(list, 18, 0, "Miner Hat")
ds_grid_add(list, 18, 1, lvl2)
ds_grid_add(list, 18, 2, 200)
ds_grid_add(list, 18, 3, "Time to mine some diamonds!")
ds_grid_add(list, 18, 4, 342)
ds_grid_add(list, 18, 5, 18)
ds_grid_add(list, 19, 0, "Deerstalker")
ds_grid_add(list, 19, 1, lvl2)
ds_grid_add(list, 19, 2, 200)
ds_grid_add(list, 19, 3, "Cap for the mystery-solver.")
ds_grid_add(list, 19, 4, 343)
ds_grid_add(list, 19, 5, 19)
ds_grid_add(list, 20, 0, "Ribbon Bow")
ds_grid_add(list, 20, 1, lvl2)
ds_grid_add(list, 20, 2, 200)
ds_grid_add(list, 20, 3, "")
ds_grid_add(list, 20, 4, 344)
ds_grid_add(list, 20, 5, 20)


ds_grid_add(list, 21, 0, "Black Headband")
ds_grid_add(list, 21, 1, lvl2)
ds_grid_add(list, 21, 2, 200)
ds_grid_add(list, 21, 3, "Be stealthy like a ninja.")
ds_grid_add(list, 21, 4, asset_get_index("sprH_HeadbandBlack"))
ds_grid_add(list, 21, 5, 21)
ds_grid_add(list, 22, 0, "White Headband")
ds_grid_add(list, 22, 1, lvl2)
ds_grid_add(list, 22, 2, 200)
ds_grid_add(list, 22, 3, "Be stealthy like a ninja.")
ds_grid_add(list, 22, 4, asset_get_index("sprH_HeadbandWhite"))
ds_grid_add(list, 22, 5, 22)
ds_grid_add(list, 23, 0, "Blue Headband")
ds_grid_add(list, 23, 1, lvl2)
ds_grid_add(list, 23, 2, 200)
ds_grid_add(list, 23, 3, "Be stealthy like a ninja.")
ds_grid_add(list, 23, 4, asset_get_index("sprH_HeadbandBlue"))
ds_grid_add(list, 23, 5, 23)
ds_grid_add(list, 24, 0, "Red Headband")
ds_grid_add(list, 24, 1, lvl2)
ds_grid_add(list, 24, 2, 200)
ds_grid_add(list, 24, 3, "Be stealthy like a ninja.")
ds_grid_add(list, 24, 4, asset_get_index("sprH_HeadbandRed"))
ds_grid_add(list, 24, 5, 24)
ds_grid_add(list, 25, 0, "Yellow Headband")
ds_grid_add(list, 25, 1, lvl2)
ds_grid_add(list, 25, 2, 200)
ds_grid_add(list, 25, 3, "Be stealthy like a ninja.")
ds_grid_add(list, 25, 4, asset_get_index("sprH_HeadbandYellow"))
ds_grid_add(list, 25, 5, 25)
ds_grid_add(list, 26, 0, "Pink Headband")
ds_grid_add(list, 26, 1, lvl2)
ds_grid_add(list, 26, 2, 200)
ds_grid_add(list, 26, 3, "Be stealthy like a ninja.")
ds_grid_add(list, 26, 4, asset_get_index("sprH_HeadbandPurple"))
ds_grid_add(list, 26, 5, 26)


list = acc_lst
ds_grid_add(list, 0, 0, "Bowtie")
ds_grid_add(list, 0, 1, lvl1)
ds_grid_add(list, 0, 2, 200)
ds_grid_add(list, 0, 3, "Tiny bowtie to look sharp.")
ds_grid_add(list, 0, 4, 347)
ds_grid_add(list, 0, 5, 0)
ds_grid_add(list, 1, 0, "Sunglasses")
ds_grid_add(list, 1, 1, lvl2)
ds_grid_add(list, 1, 2, 200)
ds_grid_add(list, 1, 3, "Shades for the cool guy...")
ds_grid_add(list, 1, 4, 348)
ds_grid_add(list, 1, 5, 1)
ds_grid_add(list, 2, 0, "Hero's Mask")
ds_grid_add(list, 2, 1, lvl2)
ds_grid_add(list, 2, 2, 200)
ds_grid_add(list, 2, 3, "Black mask for a hero!")
ds_grid_add(list, 2, 4, 349)
ds_grid_add(list, 2, 5, 2)
ds_grid_add(list, 3, 0, "Necktie")
ds_grid_add(list, 3, 1, lvl1)
ds_grid_add(list, 3, 2, 200)
ds_grid_add(list, 3, 3, "Long tie for a worker.")
ds_grid_add(list, 3, 4, 350)
ds_grid_add(list, 3, 5, 3)
ds_grid_add(list, 4, 0, "Binky")
ds_grid_add(list, 4, 1, lvl2)
ds_grid_add(list, 4, 2, 200)
ds_grid_add(list, 4, 3, "Small pacifier for the little one.")
ds_grid_add(list, 4, 4, 351)
ds_grid_add(list, 4, 5, 4)
ds_grid_add(list, 5, 0, "Snorkel Mask")
ds_grid_add(list, 5, 1, lvl2)
ds_grid_add(list, 5, 2, 200)
ds_grid_add(list, 5, 3, "Scuba mask for a sea explorer.")
ds_grid_add(list, 5, 4, 352)
ds_grid_add(list, 5, 5, 5)
ds_grid_add(list, 6, 0, "Spike Collar")
ds_grid_add(list, 6, 1, lvl2)
ds_grid_add(list, 6, 2, 200)
ds_grid_add(list, 6, 3, "This might be a safety hazard!")
ds_grid_add(list, 6, 4, 353)
ds_grid_add(list, 6, 5, 6)
ds_grid_add(list, 7, 0, "Monocle")
ds_grid_add(list, 7, 1, lvl2)
ds_grid_add(list, 7, 2, 200)
ds_grid_add(list, 7, 3, "A corrective lens for the sophisticated.")
ds_grid_add(list, 7, 4, 354)
ds_grid_add(list, 7, 5, 7)
ds_grid_add(list, 8, 0, "Mustache")
ds_grid_add(list, 8, 1, lvl2)
ds_grid_add(list, 8, 2, 200)
ds_grid_add(list, 8, 3, "This mustache is obviously fake.")
ds_grid_add(list, 8, 4, 355)
ds_grid_add(list, 8, 5, 8)
ds_grid_add(list, 9, 0, "Thick Frames")
ds_grid_add(list, 9, 1, lvl2)
ds_grid_add(list, 9, 2, 200)
ds_grid_add(list, 9, 3, "Trendy frames.")
ds_grid_add(list, 9, 4, 356)
ds_grid_add(list, 9, 5, 9)
ds_grid_add(list, 10, 0, "Clown Nose")
ds_grid_add(list, 10, 1, lvl2)
ds_grid_add(list, 10, 2, 200)
ds_grid_add(list, 10, 3, "A nose for the funny guy.")
ds_grid_add(list, 10, 4, 357)
ds_grid_add(list, 10, 5, 10)
ds_grid_add(list, 11, 0, "3D Glasses")
ds_grid_add(list, 11, 1, lvl2)
ds_grid_add(list, 11, 2, 200)
ds_grid_add(list, 11, 3, "From 2.5D to 3D?")
ds_grid_add(list, 11, 4, 358)
ds_grid_add(list, 11, 5, 11)
ds_grid_add(list, 12, 0, "Party Mask")
ds_grid_add(list, 12, 1, h_halloween)
ds_grid_add(list, 12, 2, 200)
ds_grid_add(list, 12, 3, "Holiday accessory.#S P O O K Y")
ds_grid_add(list, 12, 4, 359)
ds_grid_add(list, 12, 5, 12)
ds_grid_add(list, 13, 0, "Knitted Scarf")
ds_grid_add(list, 13, 1, lvl2)
ds_grid_add(list, 13, 2, 200)
ds_grid_add(list, 13, 3, "Stay warm through the winter!")
ds_grid_add(list, 13, 4, 360)
ds_grid_add(list, 13, 5, 13)
ds_grid_add(list, 14, 0, "Eye Patch")
ds_grid_add(list, 14, 1, lvl2)
ds_grid_add(list, 14, 2, 200)
ds_grid_add(list, 14, 3, "A pirate's life is the life for me!")
ds_grid_add(list, 14, 4, 361)
ds_grid_add(list, 14, 5, 14)

list = food_lst
unlocked_f = ds_list_create()
unlocked_e = ds_list_create()
unlocked_t = ds_list_create()
unlocked_h = ds_list_create()
unlocked_a = ds_list_create()
for (b = 0; b < ds_grid_width(food_lst); b += 1) {
    if (ds_grid_get(food_lst, b, 1) < 2)
        ds_list_add(unlocked_f, b)
    if (ds_grid_get(food_lst, b, 1) == 1)
        page_un[0] = 1
}
for (b = 0; b < ds_grid_width(egg_lst); b += 1) {
    if (ds_grid_get(egg_lst, b, 1) < 2)
        ds_list_add(unlocked_e, b)
    if (ds_grid_get(egg_lst, b, 1) == 1)
        page_un[1] = 1
}
for (b = 0; b < ds_grid_width(toy_lst); b += 1) {
    if (ds_grid_get(toy_lst, b, 1) < 2)
        ds_list_add(unlocked_t, b)
    if (ds_grid_get(toy_lst, b, 1) == 1)
        page_un[2] = 1
}
for (b = 0; b < ds_grid_width(hat_lst); b += 1) {
    if (ds_grid_get(hat_lst, b, 1) < 2)
        ds_list_add(unlocked_h, b)
    if (ds_grid_get(hat_lst, b, 1) == 1)
        page_un[3] = 1
}
for (b = 0; b < ds_grid_width(acc_lst); b += 1) {
    if (ds_grid_get(acc_lst, b, 1) < 2)
        ds_list_add(unlocked_a, b)
    if (ds_grid_get(acc_lst, b, 1) == 1)
        page_un[4] = 1
}
list2 = unlocked_f
